// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/contact/contact.proto

package br.com.soulcodesoft.protoentity;

public final class Contact {
  private Contact() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contact_ContactMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contact_ContactMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/contact/contact.proto\022\007contact\032\035" +
      "proto/contact/telephone.proto\"\267\001\n\016Contac" +
      "tMessage\022\014\n\004name\030\001 \001(\t\0221\n\004type\030\002 \001(\0162#.c" +
      "ontact.ContactMessage.TypeContact\022-\n\ntel" +
      "ephones\030\003 \003(\0132\031.contact.TelephoneMessage" +
      "\"5\n\013TypeContact\022\t\n\005AMIGO\020\000\022\r\n\tCOMERCIAL\020" +
      "\001\022\014\n\010TRABALHO\020\002B,\n\037br.com.soulcodesoft.p" +
      "rotoentityB\007ContactP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          br.com.soulcodesoft.protoentity.Telephone.getDescriptor(),
        });
    internal_static_contact_ContactMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contact_ContactMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contact_ContactMessage_descriptor,
        new java.lang.String[] { "Name", "Type", "Telephones", });
    br.com.soulcodesoft.protoentity.Telephone.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
