// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/contact/contact.proto

package br.com.soulcodesoft.protoentity;

/**
 * Protobuf type {@code contact.ContactMessage}
 */
public final class ContactMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:contact.ContactMessage)
    ContactMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContactMessage.newBuilder() to construct.
  private ContactMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContactMessage() {
    name_ = "";
    type_ = 0;
    telephones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContactMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContactMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              telephones_ = new java.util.ArrayList<br.com.soulcodesoft.protoentity.TelephoneMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            telephones_.add(
                input.readMessage(br.com.soulcodesoft.protoentity.TelephoneMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        telephones_ = java.util.Collections.unmodifiableList(telephones_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.soulcodesoft.protoentity.Contact.internal_static_contact_ContactMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.soulcodesoft.protoentity.Contact.internal_static_contact_ContactMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.soulcodesoft.protoentity.ContactMessage.class, br.com.soulcodesoft.protoentity.ContactMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code contact.ContactMessage.TypeContact}
   */
  public enum TypeContact
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AMIGO = 0;</code>
     */
    AMIGO(0),
    /**
     * <code>COMERCIAL = 1;</code>
     */
    COMERCIAL(1),
    /**
     * <code>TRABALHO = 2;</code>
     */
    TRABALHO(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AMIGO = 0;</code>
     */
    public static final int AMIGO_VALUE = 0;
    /**
     * <code>COMERCIAL = 1;</code>
     */
    public static final int COMERCIAL_VALUE = 1;
    /**
     * <code>TRABALHO = 2;</code>
     */
    public static final int TRABALHO_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeContact valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TypeContact forNumber(int value) {
      switch (value) {
        case 0: return AMIGO;
        case 1: return COMERCIAL;
        case 2: return TRABALHO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TypeContact>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TypeContact> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TypeContact>() {
            public TypeContact findValueByNumber(int number) {
              return TypeContact.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.soulcodesoft.protoentity.ContactMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final TypeContact[] VALUES = values();

    public static TypeContact valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TypeContact(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:contact.ContactMessage.TypeContact)
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>.contact.ContactMessage.TypeContact type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.contact.ContactMessage.TypeContact type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public br.com.soulcodesoft.protoentity.ContactMessage.TypeContact getType() {
    @SuppressWarnings("deprecation")
    br.com.soulcodesoft.protoentity.ContactMessage.TypeContact result = br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.valueOf(type_);
    return result == null ? br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.UNRECOGNIZED : result;
  }

  public static final int TELEPHONES_FIELD_NUMBER = 3;
  private java.util.List<br.com.soulcodesoft.protoentity.TelephoneMessage> telephones_;
  /**
   * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
   */
  @java.lang.Override
  public java.util.List<br.com.soulcodesoft.protoentity.TelephoneMessage> getTelephonesList() {
    return telephones_;
  }
  /**
   * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder> 
      getTelephonesOrBuilderList() {
    return telephones_;
  }
  /**
   * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
   */
  @java.lang.Override
  public int getTelephonesCount() {
    return telephones_.size();
  }
  /**
   * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
   */
  @java.lang.Override
  public br.com.soulcodesoft.protoentity.TelephoneMessage getTelephones(int index) {
    return telephones_.get(index);
  }
  /**
   * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
   */
  @java.lang.Override
  public br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder getTelephonesOrBuilder(
      int index) {
    return telephones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (type_ != br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.AMIGO.getNumber()) {
      output.writeEnum(2, type_);
    }
    for (int i = 0; i < telephones_.size(); i++) {
      output.writeMessage(3, telephones_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (type_ != br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.AMIGO.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    for (int i = 0; i < telephones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, telephones_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.soulcodesoft.protoentity.ContactMessage)) {
      return super.equals(obj);
    }
    br.com.soulcodesoft.protoentity.ContactMessage other = (br.com.soulcodesoft.protoentity.ContactMessage) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (type_ != other.type_) return false;
    if (!getTelephonesList()
        .equals(other.getTelephonesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (getTelephonesCount() > 0) {
      hash = (37 * hash) + TELEPHONES_FIELD_NUMBER;
      hash = (53 * hash) + getTelephonesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.soulcodesoft.protoentity.ContactMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.soulcodesoft.protoentity.ContactMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code contact.ContactMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:contact.ContactMessage)
      br.com.soulcodesoft.protoentity.ContactMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.soulcodesoft.protoentity.Contact.internal_static_contact_ContactMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.soulcodesoft.protoentity.Contact.internal_static_contact_ContactMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.soulcodesoft.protoentity.ContactMessage.class, br.com.soulcodesoft.protoentity.ContactMessage.Builder.class);
    }

    // Construct using br.com.soulcodesoft.protoentity.ContactMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTelephonesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      type_ = 0;

      if (telephonesBuilder_ == null) {
        telephones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        telephonesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.soulcodesoft.protoentity.Contact.internal_static_contact_ContactMessage_descriptor;
    }

    @java.lang.Override
    public br.com.soulcodesoft.protoentity.ContactMessage getDefaultInstanceForType() {
      return br.com.soulcodesoft.protoentity.ContactMessage.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.soulcodesoft.protoentity.ContactMessage build() {
      br.com.soulcodesoft.protoentity.ContactMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.soulcodesoft.protoentity.ContactMessage buildPartial() {
      br.com.soulcodesoft.protoentity.ContactMessage result = new br.com.soulcodesoft.protoentity.ContactMessage(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.type_ = type_;
      if (telephonesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          telephones_ = java.util.Collections.unmodifiableList(telephones_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.telephones_ = telephones_;
      } else {
        result.telephones_ = telephonesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.soulcodesoft.protoentity.ContactMessage) {
        return mergeFrom((br.com.soulcodesoft.protoentity.ContactMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.soulcodesoft.protoentity.ContactMessage other) {
      if (other == br.com.soulcodesoft.protoentity.ContactMessage.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (telephonesBuilder_ == null) {
        if (!other.telephones_.isEmpty()) {
          if (telephones_.isEmpty()) {
            telephones_ = other.telephones_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTelephonesIsMutable();
            telephones_.addAll(other.telephones_);
          }
          onChanged();
        }
      } else {
        if (!other.telephones_.isEmpty()) {
          if (telephonesBuilder_.isEmpty()) {
            telephonesBuilder_.dispose();
            telephonesBuilder_ = null;
            telephones_ = other.telephones_;
            bitField0_ = (bitField0_ & ~0x00000001);
            telephonesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTelephonesFieldBuilder() : null;
          } else {
            telephonesBuilder_.addAllMessages(other.telephones_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.soulcodesoft.protoentity.ContactMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.soulcodesoft.protoentity.ContactMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.contact.ContactMessage.TypeContact type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.contact.ContactMessage.TypeContact type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.contact.ContactMessage.TypeContact type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public br.com.soulcodesoft.protoentity.ContactMessage.TypeContact getType() {
      @SuppressWarnings("deprecation")
      br.com.soulcodesoft.protoentity.ContactMessage.TypeContact result = br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.valueOf(type_);
      return result == null ? br.com.soulcodesoft.protoentity.ContactMessage.TypeContact.UNRECOGNIZED : result;
    }
    /**
     * <code>.contact.ContactMessage.TypeContact type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(br.com.soulcodesoft.protoentity.ContactMessage.TypeContact value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.contact.ContactMessage.TypeContact type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<br.com.soulcodesoft.protoentity.TelephoneMessage> telephones_ =
      java.util.Collections.emptyList();
    private void ensureTelephonesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        telephones_ = new java.util.ArrayList<br.com.soulcodesoft.protoentity.TelephoneMessage>(telephones_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.com.soulcodesoft.protoentity.TelephoneMessage, br.com.soulcodesoft.protoentity.TelephoneMessage.Builder, br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder> telephonesBuilder_;

    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public java.util.List<br.com.soulcodesoft.protoentity.TelephoneMessage> getTelephonesList() {
      if (telephonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(telephones_);
      } else {
        return telephonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public int getTelephonesCount() {
      if (telephonesBuilder_ == null) {
        return telephones_.size();
      } else {
        return telephonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public br.com.soulcodesoft.protoentity.TelephoneMessage getTelephones(int index) {
      if (telephonesBuilder_ == null) {
        return telephones_.get(index);
      } else {
        return telephonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder setTelephones(
        int index, br.com.soulcodesoft.protoentity.TelephoneMessage value) {
      if (telephonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTelephonesIsMutable();
        telephones_.set(index, value);
        onChanged();
      } else {
        telephonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder setTelephones(
        int index, br.com.soulcodesoft.protoentity.TelephoneMessage.Builder builderForValue) {
      if (telephonesBuilder_ == null) {
        ensureTelephonesIsMutable();
        telephones_.set(index, builderForValue.build());
        onChanged();
      } else {
        telephonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder addTelephones(br.com.soulcodesoft.protoentity.TelephoneMessage value) {
      if (telephonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTelephonesIsMutable();
        telephones_.add(value);
        onChanged();
      } else {
        telephonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder addTelephones(
        int index, br.com.soulcodesoft.protoentity.TelephoneMessage value) {
      if (telephonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTelephonesIsMutable();
        telephones_.add(index, value);
        onChanged();
      } else {
        telephonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder addTelephones(
        br.com.soulcodesoft.protoentity.TelephoneMessage.Builder builderForValue) {
      if (telephonesBuilder_ == null) {
        ensureTelephonesIsMutable();
        telephones_.add(builderForValue.build());
        onChanged();
      } else {
        telephonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder addTelephones(
        int index, br.com.soulcodesoft.protoentity.TelephoneMessage.Builder builderForValue) {
      if (telephonesBuilder_ == null) {
        ensureTelephonesIsMutable();
        telephones_.add(index, builderForValue.build());
        onChanged();
      } else {
        telephonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder addAllTelephones(
        java.lang.Iterable<? extends br.com.soulcodesoft.protoentity.TelephoneMessage> values) {
      if (telephonesBuilder_ == null) {
        ensureTelephonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, telephones_);
        onChanged();
      } else {
        telephonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder clearTelephones() {
      if (telephonesBuilder_ == null) {
        telephones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        telephonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public Builder removeTelephones(int index) {
      if (telephonesBuilder_ == null) {
        ensureTelephonesIsMutable();
        telephones_.remove(index);
        onChanged();
      } else {
        telephonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public br.com.soulcodesoft.protoentity.TelephoneMessage.Builder getTelephonesBuilder(
        int index) {
      return getTelephonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder getTelephonesOrBuilder(
        int index) {
      if (telephonesBuilder_ == null) {
        return telephones_.get(index);  } else {
        return telephonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public java.util.List<? extends br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder> 
         getTelephonesOrBuilderList() {
      if (telephonesBuilder_ != null) {
        return telephonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(telephones_);
      }
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public br.com.soulcodesoft.protoentity.TelephoneMessage.Builder addTelephonesBuilder() {
      return getTelephonesFieldBuilder().addBuilder(
          br.com.soulcodesoft.protoentity.TelephoneMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public br.com.soulcodesoft.protoentity.TelephoneMessage.Builder addTelephonesBuilder(
        int index) {
      return getTelephonesFieldBuilder().addBuilder(
          index, br.com.soulcodesoft.protoentity.TelephoneMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .contact.TelephoneMessage telephones = 3;</code>
     */
    public java.util.List<br.com.soulcodesoft.protoentity.TelephoneMessage.Builder> 
         getTelephonesBuilderList() {
      return getTelephonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.com.soulcodesoft.protoentity.TelephoneMessage, br.com.soulcodesoft.protoentity.TelephoneMessage.Builder, br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder> 
        getTelephonesFieldBuilder() {
      if (telephonesBuilder_ == null) {
        telephonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            br.com.soulcodesoft.protoentity.TelephoneMessage, br.com.soulcodesoft.protoentity.TelephoneMessage.Builder, br.com.soulcodesoft.protoentity.TelephoneMessageOrBuilder>(
                telephones_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        telephones_ = null;
      }
      return telephonesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:contact.ContactMessage)
  }

  // @@protoc_insertion_point(class_scope:contact.ContactMessage)
  private static final br.com.soulcodesoft.protoentity.ContactMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.soulcodesoft.protoentity.ContactMessage();
  }

  public static br.com.soulcodesoft.protoentity.ContactMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContactMessage>
      PARSER = new com.google.protobuf.AbstractParser<ContactMessage>() {
    @java.lang.Override
    public ContactMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContactMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContactMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContactMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.soulcodesoft.protoentity.ContactMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

