// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/contact/telephone.proto

package br.com.soulcodesoft.protoentity;

public final class Telephone {
  private Telephone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contact_TelephoneMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contact_TelephoneMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/contact/telephone.proto\022\007contact" +
      "\"\220\001\n\020TelephoneMessage\022\016\n\006number\030\001 \001(\t\0222\n" +
      "\004type\030\002 \001(\0162$.contact.TelephoneMessage.T" +
      "ypeNumber\"8\n\nTypeNumber\022\013\n\007CELULAR\020\000\022\017\n\013" +
      "RESIDENCIAL\020\001\022\014\n\010TRABALHO\020\002B.\n\037br.com.so" +
      "ulcodesoft.protoentityB\tTelephoneP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_contact_TelephoneMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contact_TelephoneMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contact_TelephoneMessage_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
